remote_theme: pages-themes/slate@v0.2.0
#remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - ./EJOR_2024/Database.md
  - ./EJOR_2024/Artifact.md
  - ./EJOR_2024/Experiments.md
  - ./index.md
markdown: kramdown
